name: build

on: push

jobs:
  build:
    runs-on: 'macos-latest'

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - run: pip install -r requirements.txt pyinstaller
    - run: pyinstaller app-macos.spec
    - uses: actions/upload-artifact@v3
      with:
        name: bundle
        path: dist/prompter.app
